### ISSUE TITLE
把socket.py放进去以后没有起作用

### ISSUE THREAD

**Issue by benliangw** [falseen/PySocket#17]
您好，我把Limit_Clients目录下的socket.py放到了shadowsocks的根目录下，然后用sudo ssserver -c /etc/shadowsocks.json -d start -v命令开启shadowsocks，我限制的是10002端口只能有1个ip地址连接，但是看log好像并没有进行限制，而且手机和电脑的确能同时使用10002端口。想问一下这个是什么问题？
[shadowsocks.log](https://github.com/falseen/PySocket/files/1777225/shadowsocks.log)

**Comment by benliangw** [comment]
目录结构差不多是这样的，想问一下是我放置的位置有问题么？
![image](https://user-images.githubusercontent.com/23111424/36933998-6925d106-1f1d-11e8-80a1-aeb837c0ceb5.png)

**Comment by falseen** [comment]
不要用pip的方式安装
