### ISSUE TITLE
Limit Clients 如何使用？

### ISSUE THREAD

**Issue by WalkerWalker** [falseen/PySocket#3]
抱歉我还是比较笨，虽然你写了，但我还是一脸懵逼。。。。

> 使用说明：1.将此文件放在程序根目录中即可生效，不用做其他设置（需要重新运行程序）。

是把这个socket.py文件下载放到哪里？ 还是需要整个git库都拿下来？
我是在aws上开了一个centos的机器，在上面安装了ssserver，配置了`/etc/shadowsocks.json`

**Comment by falseen** [comment]
通过pip安装的要放到 ssserver 所在的文件夹，一般是在 python 的目录中。但我不建议这么做。我建议你直接 git clone 下来，不要安装。因为如果放到 ssserver 所在的文件夹的话可能会影响到其他 python 程序。

**Comment by WalkerWalker** [comment]
啊，我还真不知道装到哪里去了。 我which ssserver了一下，现在应该直接运行了 /bin/ssserver 里面的binary

你是说直接在我的user目录下clone 整个项目？抱歉我还是还是get不到这个很简单的事情

**Comment by falseen** [comment]
进到用户目录，输入下面的命令即可（需要安装git）：

`git clone -b master https://github.com/shadowsocks/shadowsocks.git`

运行的时候 输入 ： `python shadowsocks/shadowsocks/server.py`

注意：我这个补丁暂时不支持python3，所以你要用python2运行。不过一般的系统都是默认的python2。

**Comment by WalkerWalker** [comment]
啊，感谢感谢。git clone 和运行python我还是会的。 你是让我重新跑一个server.py的进程吗？ 我之前应该已经 pip install shadowsockets  然后 /bin/ssserver -c ${CONFIG_FILE} 开始运行这个server很久了。（其实之前是一个傻瓜化脚本直接安装的，刚刚进去看了一下脚本。其实我也不记得当初是不是用这个脚本了，一个月前了。。。）

我不是很想再重新clone shadowsocks回来再装一遍呢。。。。就是想知道应该把你的 socket.py放在什么地方，然后我重新启动一下server，试试看行不行。究竟应该放在什么地方呢？

**Comment by WalkerWalker** [comment]
哦，我看懂了。你是说最好还是git clone shadowsockets下来，然后不安装对吧。。。那我试试看吧
我要不要去aws上开个新的instance呢 T_T。。。

**Comment by WalkerWalker** [comment]
我好像找到pip安装了以后，两个源码的位置了
```
/usr/lib/python2.7/site-packages/shadowsocks/server.py
/usr/lib64/python2.7/socket.py
```

是不是可以把你的socket.py放到和server.py同一个目录下面？

话说直接拖git下来，然后运行倒是也可以，我试了一下，确实一个在看youtube，另一个就不行了。不过把第一个断了以后，第二个似乎还是一直不行，是不是要等五分钟？ 等了五分钟貌似还是不行。有点尴尬。。。

然后两个不同的port也不能同时看youtube，是不是我改了port_only就可以了？ 我明天再试一下看看

**Comment by falseen** [comment]
pip安装的一定要放到 ssserver 目录中，一般在 /usr/bin 或你当前用户的 bin 目录中。你找到的这两个位置是不行的。至于断开了之后仍然不行的问题，你要完全断开你的网络才行。不然连接会一直存在。电脑端的话一般关闭浏览器或退出SS就会立即断开连接，但是手机端的话在某些情况下即使关闭了客户端也要等五分钟才行。

port_only 的意思是如果你的服务器有多个ip的话是否只根据端口来判断。

你的不同port是同一个ip么？

**Comment by WalkerWalker** [comment]
是同一个ip，服务器有多个ip这听起来好高级，完全不能理解。 

就一台ec2机器，就一个ip，不同的port是想让多个用户访问。我刚刚成功运行了，这里close掉吧。 真是麻烦你了。总之已经pip安装了shadowsocks的话，就当作不能跑吧，反正我还是不知道放哪里。

但是可以直接git clone一个新的shadowsocks的项目回来，直接运行
```
git clone -b master https://github.com/shadowsocks/shadowsocks.git
cd shadowsocks/shadowsocks
wget https://raw.githubusercontent.com/falseen/PySocket/master/Limit_Clients/socket.py 
python server.py -c /etc/shadowsocks.json
```

然后我还在开机启动项里面加上了最后一个命令
```
/usr/bin/python /home/centos/shadowsocks/shadowsocks/server.py -c /etc/shadowsocks.json
```

至于`pip install shadowsocks` 运行的东西 和 `git clone https://github.com/shadowsocks/shadowsocks.git` 运行的东西有啥差别，我也不知道呢
